services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /home/user/projects/online-shop/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html

  php-fpm:
    build: ./docker

    volumes:
      - .:/var/www/html

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - 54324:5432

